name: Run Python Script Every Hour

on:
  schedule:
    - cron: '*/5 * * * *'  # This will run the workflow every hour
  workflow_dispatch:  # Allows you to manually trigger the workflow if needed

jobs:
  run-script:
    runs-on: ubuntu-latest  # You can use other operating systems if needed

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'  # Specify your Python version here

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Install dependencies if you have a requirements.txt file

    - name: Run Python script
      run: |
        python path/real-bot/bot.py  # Replace with the actual path to your Python script
